version: "3.9"
services:
  nginx:
   build: ./
   ports:
    - 81:80
   volumes:
    - ./age-calculator/:/var/www/html/
  php:
   build: ./age-calculator/
   expose:
    - 9000
   volumes:
    - ./age-calculator/:/var/www/html/